print("Hello Santy")
print("Hello Jash")
print("Hello Somu")
print("Hello Sunny")
print("Hello Sachin")
print("Hello stranger")
print("Hello neighbour1")
print("Hello neighbour2")
print("Hello neighbour3")
print("Waitrose")
